### ISSUE TITLE
No module named 'diffusion/qdit/models.model'

### ISSUE THREAD

**Issue by zjq0455** [Juanerx/Q-DiT#1]
Hi!

Thank u for ur contributions.

'No module named xxx' error occurred when I try to run it which means it could not find the module in local project. Why it happens (VSCODE)?

**Comment by Juanerx** [comment]
You can clone the latest repo and follow the readme file. `pip install .` installs the modules in this project.

**Comment by zjq0455** [comment]
> You can clone the latest repo and follow the readme file. `pip install .` installs the modules in this project.

Thank u for answering, I have fixed the issue.
