### ISSUE TITLE
GPTQ for DiT

### ISSUE THREAD

**Issue by Duncan1115** [Juanerx/Q-DiT#3]
Hi, your work is very nice!
I am wondering how to adopt GPTQ for DiT. May you release the code about it?

**Comment by Juanerx** [comment]
you can add `--use_gptq` in quant_main.sh to enable GPTQ.

**Comment by Duncan1115** [comment]
Thanks! 
I hope your paper will be accepted~

**Comment by Duncan1115** [comment]
@Juanerx Sorry to bother you. I have gotten the correct result of GPTQ. May you also release the code about RepQ-ViT for DiT?
