### ISSUE TITLE
Model parameter count statistics

### ISSUE THREAD

**Issue by CharvinMei** [Juanerx/Q-DiT#4]
Hi,
Your work is very nice!

In your paper, you mentioned conducting experiments using ImageNet 256x256. In Table 2, the size for Bit-width (W/A) of 16/16 is listed as 1349MB. Could you clarify which modules this value includes? My statistical result shows 674MB.

((![image](https://github.com/user-attachments/assets/53c01861-34f2-43e7-bfe2-6f2002b30324)))

**Comment by Juanerx** [comment]
We count the number of parameters for the entire DiT-XL/2 model. I believe 674M refers only to the parameter count, and the actual size should be doubled for FP16 format.

**Comment by CharvinMei** [comment]
Thank you very much for your explanation. I understand now.
